# Generated by Django 3.2.6 on 2021-08-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
