# Generated by Django 3.2.6 on 2021-09-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_genre_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Genre'),
        ),
    ]
